// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu5z0Q6djE_7EcCwwzI5F_KA21uyubXLQ',
    appId: '1:457168586785:web:e9886c4a360baee7d2bb60',
    messagingSenderId: '457168586785',
    projectId: 'purewallet-588af',
    authDomain: 'purewallet-588af.firebaseapp.com',
    storageBucket: 'purewallet-588af.appspot.com',
    measurementId: 'G-E408ZCB4PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVDVSp3hsfqRG8K2IC9DDj1wRletTddKs',
    appId: '1:457168586785:android:6064786e288d439ed2bb60',
    messagingSenderId: '457168586785',
    projectId: 'purewallet-588af',
    storageBucket: 'purewallet-588af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB55KIzok7994YT9Gfd_Tq-hxTONVFTmpo',
    appId: '1:457168586785:ios:5e16e3dfbfb6f079d2bb60',
    messagingSenderId: '457168586785',
    projectId: 'purewallet-588af',
    storageBucket: 'purewallet-588af.appspot.com',
    iosClientId: '457168586785-fi7nen020jjacs769iuh9u4m6boabqc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.purewalletSearchEngine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB55KIzok7994YT9Gfd_Tq-hxTONVFTmpo',
    appId: '1:457168586785:ios:5e16e3dfbfb6f079d2bb60',
    messagingSenderId: '457168586785',
    projectId: 'purewallet-588af',
    storageBucket: 'purewallet-588af.appspot.com',
    iosClientId: '457168586785-fi7nen020jjacs769iuh9u4m6boabqc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.purewalletSearchEngine',
  );
}
